# CEDA Labels - Centraal beheerd

# Domein labels
- name: instroom
  color: "1D76DB"
  description: Instroomprognose MBO

- name: uitval
  color: "D93F0B"
  description: Uitval analyses

- name: tech
  color: "5319E7"
  description: Technische verbeteringen

- name: project
  color: "0E8A16"
  description: Project organisatie

# Status labels
- name: needs-shaping
  color: "FBCA04"
  description: Pitch die nog gevormd moet worden
