name: Bug
description: Rapporteer een bug of probleem
type: Bug
body:
  - type: textarea
    id: description
    attributes:
      label: Beschrijving
      description: |
        Beschrijf de bug en hoe deze te reproduceren.

        Optioneel: verwacht/huidig gedrag, screenshots, logs, omgeving.
      placeholder: |
        **Wat gaat er mis?**
        ...

        **Stappen om te reproduceren:**
        1. ...

        **Screenshots / Logs (optioneel):**
        ...
    validations:
      required: true
