name: Needs Shaping
description: Ruwe ideeën die nog gevormd moeten worden tot een pitch
type: Needs shaping
body:
  - type: markdown
    attributes:
      value: |
        ## Raw idea
        Beschrijf je idee zo kort of uitgebreid als je wilt. Dit is de plek voor half-uitgewerkte gedachten, observaties, of problemen die je bent tegengekomen.

  - type: textarea
    id: idea
    attributes:
      label: Idee / Probleem
      description: Wat is het idee of probleem? Geen format vereist.
      placeholder: Beschrijf vrij wat je denkt...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context (optioneel)
      description: Achtergrond, links, screenshots, of wat verder relevant is.
      placeholder: Eventuele extra context...
    validations:
      required: false
