name: Pitch
description: Shape Up pitch voor een groter stuk werk
type: Pitch
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Opportunity
      description: Wat is het echte probleem? Voor wie? Evidence, voorbeelden, context.
      placeholder: Beschrijf het probleem...
    validations:
      required: true

  - type: dropdown
    id: appetite
    attributes:
      label: Appetite (timebox)
      description: Hoeveel tijd willen we hieraan besteden?
      options:
        - Small (1-2 dagen)
        - Medium (3-4 dagen)
        - Large (5-6 dagen)
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: High-level aanpak, misschien enkele key elements.
      placeholder: Beschrijf de oplossingsrichting...
    validations:
      required: false

  - type: textarea
    id: risks
    attributes:
      label: Risks / Rabbit holes
      description: Welke valkuilen moeten we vermijden?
      placeholder: Beschrijf risico's...
    validations:
      required: false

  - type: textarea
    id: nogos
    attributes:
      label: No-Gos
      description: Wat doen we expliciet NIET in deze versie?
      placeholder: Beschrijf no-gos...
    validations:
      required: false

  - type: input
    id: validated
    attributes:
      label: Gevalideerd met
      description: Met wie is deze pitch afgestemd? Gebruik @username om te taggen.
      placeholder: "@username"
    validations:
      required: false

  - type: input
    id: sparring
    attributes:
      label: Sparring partner
      description: Met wie kun je snel sparren? Gebruik @username om te taggen.
      placeholder: "@username"
    validations:
      required: false
