name: Pitch
description: Shape Up pitch voor een groter stuk werk
type: Pitch
body:
  - type: markdown
    attributes:
      value: |
        ## Pitch aanmaken
        Gebruik dit formulier om een Shape Up pitch te beschrijven.

  - type: textarea
    id: problem
    attributes:
      label: Problem / Opportunity
      description: Wat is het echte probleem? Voor wie? Evidence, voorbeelden, context.
      placeholder: Beschrijf het probleem...
    validations:
      required: true

  - type: dropdown
    id: appetite
    attributes:
      label: Appetite (timebox)
      description: Hoeveel tijd willen we hieraan besteden?
      options:
        - Small (1-2 werkdagen)
        - Large (hele sprint, 6-8 werkdagen)
        - Custom
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: High-level aanpak, misschien enkele key elements.
      placeholder: Beschrijf de oplossingsrichting...
    validations:
      required: true

  - type: textarea
    id: risks
    attributes:
      label: Risks / Rabbit holes
      description: Welke valkuilen moeten we vermijden? Welke elementen hebben risico om in te verdwalen?
      placeholder: Beschrijf risico's...
    validations:
      required: false

  - type: textarea
    id: nogos
    attributes:
      label: No-Gos
      description: Wat doen we expliciet NIET in deze versie?
      placeholder: |
        -
        -
    validations:
      required: false

  - type: input
    id: validated
    attributes:
      label: Gevalideerd met
      description: Naam collega / key-user met wie deze pitch is afgestemd
      placeholder: Naam...
    validations:
      required: false

  - type: input
    id: sparring
    attributes:
      label: Sparring partner
      description: Met wie kun je gedurende deze pitch snel sparren?
      placeholder: Naam...
    validations:
      required: false
