name: Task
description: Taak, item of werk unit
type: Task
project: CEDA Board
body:
  - type: textarea
    id: description
    attributes:
      label: Beschrijving
      description: |
        Wat moet er gedaan worden?

        Je kunt hier ook acceptatiecriteria en context toevoegen.
      placeholder: |
        Beschrijf de taak...

        **Acceptatiecriteria:**
        - [ ] ...

        **Context:**
        Links of achtergrond...
    validations:
      required: true
