name: Task
description: Taak, item of werk unit
type: Task
body:
  - type: textarea
    id: description
    attributes:
      label: Beschrijving
      description: Wat moet er gedaan worden?
      placeholder: Beschrijf de taak...
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptatiecriteria
      description: Wanneer is deze taak klaar?
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: false
